services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootroot  # <--- 注意！密码改成了 rootroot (8位)
      - POSTGRES_DB=ny_taxi
    volumes:
      - pgdata:/var/lib/postgresql/data # <--- 这里改成了 Docker 内部卷
    ports:
      - "5433:5432"  # <--- 这里改成了 5433

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8081:80"

volumes:
  pgdata:  # <--- 声明这个新卷